<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Zend Framework Quickstart Application</title>
	<?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
</head>
<body>
	<div id="main">
		<h1>Poker Hud Tracker</h1>
		
		<?php echo $this->layout()->content ?>
		
	</div>
</body>
</html>